[package]
name = "jamurust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
clap = "2.33.3"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
bindgen = "0.53.1"
