name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Fetch submodules
        run: git submodule update --init
      - name: Compile opus
        run: cd opus && ./autogen.sh && ./configure --enable-static --disable-shared --enable-custom-modes --disable-hardening && make
      - name: Build
        run: cargo build --verbose --target=x86_64-unknown-linux-gnu
      - name: Run tests
        run: cargo test --verbose
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: linux-binaries
          path: |
            target/x86_64-unknown-linux-gnu/debug/jam-listener
          if-no-files-found: error
